### ISSUE TITLE
Ktor 3.4.0 runtime error: NoSuchMethodError Route.getParent() in closestDI()

### ISSUE THREAD

**Issue by wjb-fw** [kosi-libs/Kodein#502]
After upgrading to Ktor 3.4.0, applications using the Kodein Ktor extension crash at runtime with a NoSuchMethodError due to the missing Route.getParent() method.

```
java.lang.NoSuchMethodError: 'io.ktor.server.routing.Route io.ktor.server.routing.Route.getParent()'
    at org.kodein.di.ktor.ClosestKt.closestDI(Closest.kt:45)
```

This worked correctly on Ktor 3.3.3 with the same Kodein version (7.30.0).
